package pharm;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * A prescription
 * Contains the provider name, the patient name, the NDC of
 * the medication, the date received, the date filled, the frequency,
 * the number of refills allowed, and the status (filled or not filled)
 * An id is generated by the pharmacy upon receipt
 * @author Gaganajit Singh
 *
 */
public class Prescription implements Serializable{

	private static final long serialVersionUID = 1L;

	public enum Status { UNFILLED, FILLED;}
	
	private String id;
	private String providerName;
	private String patientName;
	private String drugNDC;
	private LocalDateTime recvDate;
	private LocalDateTime fillDate;
	private int frequency;
	private int refills;
	private Status status;
	
	public Prescription(String providerName, String patientName,String drugNDC, int frequency, int refills) {
		super();
		this.id = "";
		this.providerName = providerName;
		this.patientName = patientName;
		this.drugNDC = drugNDC;
		this.frequency = frequency;
		this.refills = refills;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProviderName() {
		return providerName;
	}

	public void setProviderName(String providerName) {
		this.providerName = providerName;
	}

	
	public String getPatientName() {
		return patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	public String getDrugNDC() {
		return drugNDC;
	}

	public void setDrugNDC(String drugNDC) {
		this.drugNDC = drugNDC;
	}

	public LocalDateTime getRecvDate() {
		return recvDate;
	}

	public void setRecvDate(LocalDateTime recvDate) {
		this.recvDate = recvDate;
	}

	public LocalDateTime getFillDate() {
		return fillDate;
	}

	public void setFillDate(LocalDateTime fillDate) {
		this.fillDate = fillDate;
	}

	public int getFrequency() {
		return frequency;
	}

	public void setFrequency(int frequency) {
		this.frequency = frequency;
	}

	public int getRefills() {
		return refills;
	}

	public void setRefills(int refills) {
		this.refills = refills;
	}

	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Override
	public String toString() {
		String newline = System.lineSeparator();
		return "id: " + id + newline + 
				"Provider Name : " + providerName + newline +
				"Patient Name: " + patientName + newline +
				"NDC: " + drugNDC + newline + 
				 "Date received: "+ recvDate + newline +
				 "Date filled: " + fillDate +  newline +
				 "frequency: " + frequency + ", refills: " + refills + newline +
				 "status: " + status;
		
	}
	
	
	

}
